def rename_columns_name(df_processing):
    """ Rename columns names to a more readable format. """
    df_processing.rename(columns={
        'number'                                : 'Number',
        'caller_id'                             : 'Caller',
        'u_incident_type'                       : 'Incident_Type',
        'impact'                                : 'Impact',
        'short_description'                     : 'Short_Description',
        'u_impacted_area'                       : 'Area',
        'u_impacted_business_unit'              : 'BU',
        'assignment_group'                      : 'Assignment_Group',
        'assignment_group.manager.email'        : 'AG_Manager_Email',
        'assigned_to'                           : 'Assigned',
        'assigned_to.email'                     : 'Assigned_Email',
        'u_site'                                : 'Site',
        'u_reporting_level'                     : 'Level',
        'incident_state'                        : 'Incident_State',
        'u_service'                             : 'Service',
        'u_service.u_accountmanager.email'      : 'Service_AccountManager_Email',
        'u_service.owned_by.email'              : 'Service_OwnedByEmail',
        'u_resolution_sla.percentage'           : 'SLA',
        'opened_at'                             : 'Opened',
        'u_accepted_at'                         : 'Accepted',
        'sys_updated_on'                        : 'Updated',
        'u_target_resolution_time'              : 'TRT',
        'u_supplier'                            : 'Supplier',
        'cmdb_ci'                               : 'CI_CMDB',
        'cmdb_ci.category'                      : 'CI_Category',
        'cmdb_ci.u_folder'                      : 'CI_Folder',
        'cmdb_ci.manufacturer'                  : 'CI_Manufacturer',
        'cmdb_ci.model_id'                      : 'CI_Model_ID',
        'cmdb_ci.model_number'                  : 'CI_Model_Number',
        'cmdb_ci.serial_number'                 : 'CI_Serial_Number',
        'cmdb_ci.asset_tag'                     : 'CI_Asset_Tag',
        'u_complaint_reason'                    : 'Complaint_Reason',
        'reassignment_count'                    : 'Reassignment_Count',
        'u_reassign_reason'                     : 'Reassign_Reason',
        'reopen_count'                          : 'Reopen_Count',
        'u_date_worked'                         : 'Date_Worked',
        'u_effort_service'                      : 'Effort_Service',
        'u_time_worked_total'                   : 'Time_Worked_Total',
        'u_resolution_sla.duration'             : 'SLA_Duration',
        'u_resolution_sla.business_percentage'  : 'SLA_Business_Percentage',
    }, inplace=True)

    return df_processing
